name: Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Build x64 Release
        shell: cmd
        run: msbuild Osiris.sln /p:Platform=x64 /p:Configuration=Release

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: Osiris-x64-Release-DLL
          path: |
            **/x64/Release/*.dll
